[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/getsitemap"
  status = 200
  force = true